baseURL = "www.solarnimise.cz"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Pro firmy"
  URL = "#firmy"
  weight = 2

  [[menu.header]]
  name = "Pro domy"
  URL = "#domy"
  weight = 3

  [[menu.header]]
  name = "Kontaktujte nás!"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "Pro firmy"
  URL = "#firmy"
  weight = 2

  [[menu.footer]]
  name = "Pro domy"
  URL = "#domy"
  weight = 3

  [[menu.footer]]
  name = "Kontaktujte nás!"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "firmy", "firmy_nabidka", "firmy_body", "domy", "domy_nabidka", "domy_body", "client-and-work", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "SOLÁRNÍ MISE"
    text2 = "__"

  [params.footer]
      copyright = "Created by: Ondřej Baše"
      [params.footer.radity_logo]
        x = "img/general/ob_logo.png"
        _2x = "img/general/ob_logo@2x.png"
        alt = "Created by: Ondřej Baše"